### ISSUE TITLE
Config overrrides not working

### ISSUE THREAD

**Issue by KimNorgaard** [wllfaria/ledger.nvim#3]
Thank you for this plugin. It's very nice :)

When overriding the configuration options that use metatables I get an error that the functions called on the metatable does not exist.

This config:

```lua
	add({
		source = "wllfaria/ledger.nvim",
		depends = {
			"nvim-treesitter/nvim-treesitter",
		},
	})
	local opts = {
		extensions = {
			"ldg",
		},
		snippets = {
			cmp = {
				enabled = true,
			},
			luasnip = {
				enabled = false,
			},
			native = {
				enabled = false,
			},
		},
	}
	require("ledger").setup(opts)

```

produces this error:

```
...-mini/site/pack/deps/opt/ledger.nvim/lua/ledger/init.lua:44: attempt to call method 'is_enabled' (a nil value)
```

If I override `opts.snippets:is_enabled()` it works:

```lua
	add({
		source = "wllfaria/ledger.nvim",
		depends = {
			"nvim-treesitter/nvim-treesitter",
		},
	})
	local opts = {
		extensions = {
			"ldg",
		},
		snippets = {
			cmp = {
				enabled = true,
			},
			luasnip = {
				enabled = false,
			},
			native = {
				enabled = false,
			},
		},
	}
	function opts.snippets:is_enabled()
		return true
	end
	require("ledger").setup(opts)
```

I'm guessing this is caused by the way `default_config` is initialized at https://github.com/wllfaria/ledger.nvim/blob/main/lua/ledger/config.lua#L118 - when overriding the configuration, the `setmetatable()` calls are also overridden.

**Comment by wllfaria** [comment]
Hey! thanks for this issue, i'll push up a fix today in a couple hours after i get off work! thanks for pointing this out

**Comment by KimNorgaard** [comment]
> Hey! thanks for this issue, i'll push up a fix today in a couple hours after i get off work! thanks for pointing this out

No rush. The workaround works but thank you for fixing it nonetheless :)
